### ISSUE TITLE
panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by H3rby7** [helm/chart-testing#248]
**Is this a request for help?**

Well, it's a bug that bothers me so somewhat yes

---

# BUG REPORT

```
ct lint --debug
Linting charts...
------------------------------------------------------------------------------------------------------------------------
 Configuration
------------------------------------------------------------------------------------------------------------------------
Remote: origin
TargetBranch: master
Since: HEAD
BuildId: 
LintConf: /etc/ct/lintconf.yaml
ChartYamlSchema: chart_schema.yaml
ValidateMaintainers: false
ValidateChartSchema: true
ValidateYaml: true
CheckVersionIncrement: true
ProcessAllCharts: false
Charts: []
ChartRepos: [https://charts.bitnami.com/bitnami]
ChartDirs: [charts]
ExcludedCharts: []
HelmExtraArgs: 
HelmRepoExtraArgs: []
Debug: true
Upgrade: false
SkipMissingValues: false
Namespace: 
ReleaseLabel: 
------------------------------------------------------------------------------------------------------------------------
>>> helm version --short
>>> git rev-parse --is-inside-work-tree
>>> git merge-base origin/master HEAD
>>> git diff --find-renames --name-only myshashashashashasha -- charts
------------------------------------------------------------------------------------------------------------------------
 Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
 my-service => (version: "1.0.0", path: "charts/my-service")
------------------------------------------------------------------------------------------------------------------------
panic: runtime error: index out of range [1] with length 1
goroutine 1 [running]:
github.com/helm/chart-testing/v3/pkg/chart.(*Testing).processCharts(0xc00007f860, 0xc0000cd778, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/project/pkg/chart/chart.go:323 +0x11f7
github.com/helm/chart-testing/v3/pkg/chart.(*Testing).LintCharts(0xc00007f860, 0x6, 0x93ad5f, 0x6, 0x93a342, 0x4)
	/home/circleci/project/pkg/chart/chart.go:382 +0x4e
github.com/helm/chart-testing/v3/ct/cmd.lint(0xc00009cdc0, 0xc00012a2f0, 0x0, 0x1, 0x0, 0x0)
	/home/circleci/project/ct/cmd/lint.go:86 +0x2b7
github.com/spf13/cobra.(*Command).execute(0xc00009cdc0, 0xc00012a2e0, 0x1, 0x1, 0xc00009cdc0, 0xc00012a2e0)
	/home/circleci/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:838 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc00009cb00, 0x442027, 0xce6660, 0xc00004a778)
	/home/circleci/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	/home/circleci/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883
github.com/helm/chart-testing/v3/ct/cmd.Execute()
	/home/circleci/project/ct/cmd/root.go:57 +0x2b
main.main()
	/home/circleci/project/ct/main.go:22 +0x20
```

**Version of Helm and Kubernetes**:

I am using quay.io/helmpack/chart-testing:v3.0.0 without connection to my kubernetes

**What happened**:
The go-routine panics

**What you expected to happen**:
The program tells me to bump the version

**How to reproduce it** (as minimally and precisely as possible):
1. Setup a repository with a master branch and a chart(s)
1. Checkout another branch (e.g. test/smallChange)
1. Change something inside the template section of your chart
1. `ct lint` fails with a internal go routine panic.

**Anything else we need to know**:
Inside my template I only changed the name of an ENV var
```
- name: SFTP_PASSWORD
to
- name: SFTP_PASSWORDDEV

**Comment by H3rby7** [comment]
A quick dive into the code did reveal my config error:

```
      --chart-repos strings            Additional chart repositories for dependency resolutions.
                                       Repositories should be formatted as 'name=url' (ex: local=http://127.0.0.1:8879/charts).
                                       May be specified multiple times or separate values with commas
```
I was specifying my repository wrong by just providing: 
`-e CT_CHART_REPOS="https://charts.bitnami.com/bitnami"` instead of `-e CT_CHART_REPOS="bitnami=https://charts.bitnami.com/bitnami"` to my docker container.

**Comment by dimitarvdimitrov** [comment]
I encountered the same error on version 3.7.0 (1d3feac8e5ca55ccf11521ff297ccee7f09aa749)

```

panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/helm/chart-testing/v3/pkg/chart.(*Testing).processCharts(0x140002e8200, 0x140002179f8)
	github.com/helm/chart-testing/v3/pkg/chart/chart.go:334 +0xd9c
github.com/helm/chart-testing/v3/pkg/chart.(*Testing).InstallCharts(...)
	github.com/helm/chart-testing/v3/pkg/chart/chart.go:405
github.com/helm/chart-testing/v3/ct/cmd.install(0x14000298780?, {0x10522f256?, 0x6?, 0x6?})
	github.com/helm/chart-testing/v3/ct/cmd/install.go:105 +0x25c
github.com/spf13/cobra.(*Command).execute(0x14000298780, {0x140000c0360, 0x6, 0x6})
	github.com/spf13/cobra@v1.5.0/command.go:872 +0x4d0
github.com/spf13/cobra.(*Command).ExecuteC(0x14000298280)
	github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.5.0/command.go:918
github.com/helm/chart-testing/v3/ct/cmd.Execute()
	github.com/helm/chart-testing/v3/ct/cmd/root.go:57 +0x24
main.main()
	./main.go:22 +0x20
```

I think it's reasonable to expect ct to _not_ panic when this happens. Can we reopen this?
